## Pythonプログラムの実行方法/How to run a Python program

* Pythonは近年，画像認識や機械学習等の人工知能研究分野で広く用いられているプログラミング言語です．

* Pythonの基本的な文法をプログラムを交えて説明します．

* Python is a programming language that has recently been widely used in artificial intelligence research fields such as image recognition and machine learning.

* Explain the basic syntax of Python with programs.
---
### モジュール/module

* モジュールとはPythonにおいて特定の計算を便利に行う，簡単に記述するためのプログラム群であり，C言語のライブラリに相当するものです．

* A module is a group of programs that performs a specific calculation in Python conveniently and easily, and is equivalent to a library in C language.
---
### print文/print statement

* 定義した変数などを表示するためにはprint関数（print文）を用います．

* print関数の引数として複数の値を指定することで，一度に複数の情報を表示することができます.

* The print function (print statement) is used to display defined variables and other information.

* By specifying multiple values as arguments to the print function, multiple pieces of information can be displayed at once.

In [ ]:
print("Hello world!")
print(1)
print("abc", 123)

Hello world!
1
abc 123


Pythonの代表的な変数の型/Typical Python variable types

* 数値型：整数，浮動小数点数，複素数
 - C言語のようなint, floatなどの型宣言は必要ありません

* Numeric types: integer, floating-point, complex
 - No need for int, float, etc. type declarations like in C
---
* コンテナ：リスト，タプル，辞書，集合
  - 型の混在が可能で，基本的にどんな型のデータでも代入可能

* Containers: lists, tuples, dictionaries, sets
  - Allows for mixed types, basically any type of data can be assigned
---
* 文字列
  - シングルクォート (') またはダブルクォート (") で囲むことで文字列として表現

* character string
  - Expressed as a string by enclosing in single (') or double (") quotes
---
* 定数：真偽値(True, False)，None(C言語のNULLに相当)

* Constants: True, False, None (equivalent to NULL in C language)
---
* 以下では，代表的な型とPythonの文法についてプログラムを交えて説明します．

* The following is an explanation of typical types and Python syntax with programs.

* Pythonで説明をコメントとして記述したり不要なコードをコメントアウトしたりする場合は#を使う。

* In Python, use # to write descriptions as comments or to comment out unnecessary code.

In [ ]:
# 整数，浮動小数点数/Integer, floating point number
i = 10
f = 0.001

# コンテナ（リスト，タプル，辞書，集合）/Containers (lists, tuples, dictionaries, sets)
l = [1, 0.01, "abcd"] # Use square brackets '[]' to define a list
t = (3, -4.5, "defg") # Use round brackets '()' to define tuples
d = {"a": 1.0, "b": 2.0, "c": 3.0} # A dictionary is generated by writing key/value pairs in brackets '{}' as key: value
s = {1, 2, 3} # An object of type set can be created by enclosing the element in braces '{}'

# 真偽値/True False
b1 = True
b2 = False

# None
n = None

### 文字列/character string

* 文字列はダブルクォート「"」で囲むことで定義します．

* Strings are defined by enclosing them in double quotes "".

#### 文字列の整形方法/How to format strings

* C言語のprintf系関数のようなものです．

* 「%」演算子を利用します．

* 複数の変数を文字列に代入する場合は「(...)」を用います．

* It is like the printf functions of the C language.

* Use the "%" operator.

* To assign multiple variables to a string, use "(...)". is used to assign multiple variables to a string.

（下記プログラム参照）
(See program below)

In [ ]:
# + 演算子で連結することが可能/+ operator can be used to combine
string1 = "abc" + "def"
print(string1)

# 文字列の整形方法/How to format strings
# 1. 一つの変数の場合/for a single variable
value = 10
string2 = "integer: %d" % value
print(string2)

# 2. 複数の場合/for multiple variables
value1 = 10
float_val1 = 0.01
str1 = "abc"
string3 = "integer: %d, float value: %f, string: %s" % (value1, float_val1, str1)
print(string3)

abcdef
integer: 10
integer: 10, float value: 0.010000, string: abc


#### 制御構文/control syntax

* PythonでもC言語と同様の制御構文が用意されています．

 - if文
 - while文
 - for文 

* Python provides the same control syntax as C.

 - if statement
 - while statement
 - for statement

* C言語の大きな特徴としてこれらの制御構文の対象範囲をインデント（スペース4つまたは2つ）で表現することが挙げられます．

* スペースの数はプログラム内で統一する必要があります．

* One of the main features of the C language is that the scope of these control constructs is expressed by indentation (four or two spaces).

* The number of spaces must be consistent within a program.

In [ ]:
# if文/if statement
a = 0.5
if a < 0:
    print("negative value")
elif a > 0:
    print("positive value")
else:
    print("zero")

# while文/while statement
print("==========")
b = 0
while b < 5:
    print(b)
    b += 1

# for文/for statement
print("==========")
c = [0.1, 2.34, 5.6, 7.89]
for x in c:
    print(x)

positive value
0
1
2
3
4
0.1
2.34
5.6
7.89


#### 関数/Functions

* Pythonの関数は「def」で定義を行います．

* 関数の定義でも上の制御構文と同様にインデントを用いて範囲を指定します．

* Python functions are defined using "def".

* In the function definition, indentation is used to specify the range, as in the control syntax above.

In [ ]:
# 関数定義/function definition
def sample_func1(x, y):
    z = x + y
    return z
  
# 関数の実行/Execute Function
a = 10
b = 20
c = sample_func1(a, b)
print(c)

30


#### 多重代入/multiple substitution

* C言語と異なり，複数の値を同時にreturnできる．

* Unlike the C language, multiple values can be returned simultaneously.

In [ ]:
def sample_func2(x, y):
    x = a + 1
    y = b * 2
    return x, y
  
c, d = sample_func2(1, 2)
print(c, d)

11 40


#### モジュールのインポートと実行/Import and run modules

* モジュールは「import」を用いることでプログラム内で使用することが可能です．

* ここでは，行列計算のモジュールである「Numpy」を使用してみます．

* The module can be used in a program by using "import".

* Here, we will use "Numpy", a module for matrix computation.

In [ ]:
# 通常の読み込み/Normal reading
import numpy

# numpyという関数をnpという名前で使用できるように読み込む/Read a function called numpy so that it can be used with the name np
import numpy as np

# numpy.linalgの中のnormという関数を読み込む（他は読み込まない）/Read the function named norm in numpy.linalg (and no others)
from numpy.linalg import norm

***
## Numpyの基本的な使い方/Basic usage of Numpy

* 画像認識や機械学習のプログラムでは，Numpyを用いてデータの操作を行います．

* 以下では，Numpyの基本的な使い方をプログラムを通じて学びます．

* Image recognition and machine learning programs use Numpy to manipulate data.

* In the following, you will learn the basic usage of Numpy through programs.
---
### N次元配列/N-dimensional array：ndarray

* Numpyでは上のリストやタプルとは異なり，型を統一する必要があります．

* In Numpy, unlike lists and tuples above, we need to unify the types.

In [ ]:
import numpy as np

a = np.array([[0, 0, 1], [0, 0, 2]], dtype=np.float32) # dtype=***で配列要素の型を決めています/dtype=*** determines the type of array elements
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
print(a)
print(b)

# 行列の演算（和・積）/Matrix operations (summation/product)
c = a + b
d = a * b  # * は要素ごとの掛け算です/* is per-element multiplication
print(c)
print(d)

# （数学的な）行列の掛け算/(Mathematical) matrix multiplication
e = np.dot(a, b.T)   # b.Tは行列bの転置を表しています/b.T represents the transpose of the matrix b
print(e)

[[0. 0. 1.]
 [0. 0. 2.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 4.]
 [4. 5. 8.]]
[[ 0.  0.  3.]
 [ 0.  0. 12.]]
[[ 3.  6.]
 [ 6. 12.]]


### 行列の扱い方/How to handle matrices

#### 特定の要素を取り出す（インデキシング）/Extracting specific elements (indexing)

* `a[i, j]`：行列aの`(i, j)`要素を取り出します．

* `a[i, j]`: extracts `(i, j)` elements of matrix a.

####  特定の範囲を切り出す（スライシング）/Cutting out a specific area (slicing)

* 範囲を指定する際にはコロン「:」を用います

* `a[i,:]`：行列aの`i`行目（のベクトル）

* `a[:,j]`：行列aの`j`列目（のベクトル）

* `a[:,0:3]`：行列aの`0, 1, 2`列目の部分行列

* Use a colon ":" to specify a range.

* `a[i,:]`: row `i` of matrix a (vector of)

* `a[:,j]`: column `j` of matrix a (vector of)

* `a[:,0:3]`: the `0, 1, 2` column submatrix of matrix a

#### ファンシーインデキシング/fancy indexing

* 条件に合致する特定の要素のみを取り出します．

* 認識を失敗したデータだけを取り出す場合などに用いることができる便利な機能です．

* Extracts only the specific elements that match the condition.

* This is a convenient function that can be used to extract only the data that failed to be recognized.

In [ ]:
# インデキシング/indexing
a_elem = a[0, 2]
print(a_elem)

# スライシング/slicing
a_slice1 = a[1, :]
a_slice2 = a[:, 2]
print(a_slice1)
print(a_slice2)

b_slice = b[1, 0:2]
print(b_slice)

# ファンシーインデキシング/fancy indexing
a = np.array([1, 0, 1, 0, 0], dtype=np.int32)
b = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype=np.float32)
print(b[:, a == 1])

1.0
[0. 0. 2.]
[1. 2.]
[4. 5.]
[[0. 2.]
 [5. 7.]]


### Numpyの便利な関数/Useful Functions in Numpy

* Numpyには行列を演算するための便利な関数が多数含まれています．

* 以下では，いくつかの関数を紹介します.

* 興味のある方は下記の公式referenceページへアクセスしてください．

* Numpy includes a number of useful functions for matrix operations.

* Below are some of the functions.

* If you are interested, please visit the official reference page below.

[Numpy Reference (関数一覧の公式ページ)](https://docs.scipy.org/doc/numpy/reference/)

In [ ]:
a = np.array([0,1,2], dtype=np.float32)

# exp(指数関数を要素ごとに計算)/exp(exponential function calculated by element)
print(np.exp(a))
# power(累乗)/power(power)
print(np.power(a, 2))


# 集計用の関数(非ゼロの要素数を計算)/Aggregate function (computes the number of non-zero elements)
b = np.array([1, 0, 1, 0, 0], dtype=np.int32)
print(np.count_nonzero(b))

[1.        2.718282  7.3890557]
[0. 1. 4.]
2
